version: '3.8'

services:
  nethops-server:
    build: 
        context: ../../
        dockerfile: ./docker/server/Dockerfile
    container_name: nethops-server
    working_dir: /scripts
    ports:
      - "24558:1194/udp"
    volumes:
      - ../../data2:/etc/openvpn 
    privileged: true
    restart: always
