
FROM golang:1.20.7-alpine3.18

RUN apk --no-cache add ca-certificates curl
RUN apk update

RUN apk add zsh git
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="ys"/g' /root/.zshrc

RUN apk add openssl openvpn iptables

RUN apk add nano tmux make bind-tools mtr bash
